# dacho/Cargo.toml

[package]
name        = "dacho"
version     = "0.1.0"
authors     = ["mochou-p"]
edition     = "2021"
description = "Dacho - Vulkan engine"
repository  = "https://github.com/mochou-p/dacho"
license     = "MIT OR Apache-2.0"
keywords    = ["vulkan", "engine", "renderer", "ash", "winit"]
categories  = ["game-development", "game-engines", "graphics", "rendering", "rendering::engine"]

[dependencies]
anyhow            = "1.0.81"
ash               = "0.37.3"
ash-window        = "0.12.0"
raw-window-handle = "0.5.0"
winit             = { version = "0.29.15", features = ["rwh_05"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

