# dacho/core/components/Cargo.toml

[package]
name         = "dacho-components"

edition      = "2021"
rust-version = "1.85.0"

authors      = ["mochou-p"]
license      = "MIT OR Apache-2.0"

[dependencies]
dacho-mesh-c   = { path = "mesh"   }
dacho-camera-c = { path = "camera" }

