# dacho/core/shader/Cargo.toml

[package]
name         = "dacho-shader"

edition      = "2021"
rust-version = "1.84.0"

authors      = ["mochou-p"]
license      = "MIT OR Apache-2.0"

[features]
wgsl = ["dacho-wgsl"]

[dependencies]
dacho-wgsl = { path = "wgsl", optional = true }

